language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-22.0.0

    # The SDK version used to compile your project
    - android-21
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - chmod +x gradlew

install:
  - ./gradlew assemble

script:
  - ./gradlew test
branches:
  only:
    - master
notifications:
  email:
      - hex0r@me.com
      - ducva2410@gmail.com