language: android
jdk:
  - oraclejdk7
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-19

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - android-21
    - build-tools-21.1.2

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
gradle check
./gradlew check
gradle assemble
./gradlew assemble
# blacklist
branches:
  except:
    - legacy

# whitelist
branches:
  only:
    - master
notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email:
      - hex0r@me.com
      - ducva2410@gmail.com
      on_success: [always|never|change] # default: change
      on_failure: [always|never|change] # default: always