language: android
jdk:
  - oraclejdk7
android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra-google-m2repository
    - extra-android-m2repository

branches:
  only:
    - master
notifications:
  email:
      - hex0r@me.com
      - ducva2410@gmail.com